/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author
 *
 * I Putu Trisna Budi Utama      | 210711438
 * Boniface Fredo Ronan Antolino | 210711446
 * 
 */

import javax.swing.JOptionPane;
import control.KendaraanControl;
import exception.*;
import model.Kendaraan;

public class view extends javax.swing.JFrame {

    private KendaraanControl kc;
    String action, type;

    public view() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        kc = new KendaraanControl();
        showData();
    }
    
    public void setComponent(boolean val){
        idInput.setEnabled(val);
        brandVehicleinput.setEnabled(val);
        productionYearInput.setEnabled(val);
        platNumberInput.setEnabled(val);
        CarRBtn.setEnabled(val);
        motorcycleRBtn.setEnabled(val);
        totalPassengerInput.setEnabled(val);
        strokeTypeInput.setEnabled(val);
        
        saveBtn.setEnabled(val);
        cancelBtn.setEnabled(val);
    }
    
    public void setEditDeleteBtn(boolean val){
        updateBtn.setEnabled(val);
        deleteBtn.setEnabled(val);
    }
    
    public void clearTxt(){
        idInput.setText("");
        brandVehicleinput.setText("");
        productionYearInput.setText("");
        platNumberInput.setText("");
        searchInput.setText("");
        totalPassengerInput.setText("");
        strokeTypeInput.setText("");
    }
    
    public void isEmptyException() throws IsEmptyException{
       if(idInput.getText().isEmpty() || brandVehicleinput.getText().isEmpty() || productionYearInput.getText().isEmpty() 
               || platNumberInput.getText().isEmpty() );
       throw new IsEmptyException();
    }
    
    public void InvalidIdException() throws InvalidIDException{
        if(idInput.getText().length() < 5 || idInput.getText().length() > 8 ){
            throw new InvalidIDException();
        }
    }
    
    public void chooseTypeException() throws ChooseTypeException{
         if(!CarRBtn.isSelected() && !motorcycleRBtn.isSelected()){
            throw new ChooseTypeException();
        }
    }
    
    public void showData(){
        dataCarTxa.setText(kc.showDataMobil());
        dataMotoTxa.setText(kc.showDataMotor());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        backgroundPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        datakelompokLbl = new javax.swing.JPanel();
        namaKelompoklbl = new javax.swing.JLabel();
        anggota1Lbl = new javax.swing.JLabel();
        anggota2Lbl = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        actionpanel = new javax.swing.JPanel();
        idvehicleLbl = new javax.swing.JLabel();
        brandVehicleLbl = new javax.swing.JLabel();
        productionYearLbl = new javax.swing.JLabel();
        platNumberLbl = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        brandVehicleinput = new javax.swing.JTextField();
        productionYearInput = new javax.swing.JTextField();
        platNumberInput = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        action2Panel = new javax.swing.JPanel();
        totalPassengerLbl = new javax.swing.JLabel();
        totalPassengerInput = new javax.swing.JTextField();
        strokeTypeLbl = new javax.swing.JLabel();
        strokeTypeInput = new javax.swing.JTextField();
        CarRBtn = new javax.swing.JRadioButton();
        motorcycleRBtn = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        showDataPanel = new javax.swing.JPanel();
        dataCarLbl = new javax.swing.JLabel();
        dataMotoLbl1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataCarTxa = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataMotoTxa = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 211, 163));

        titleLbl.setFont(new java.awt.Font("Bodoni MT Condensed", 0, 60)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Object Persistance 1");

        namaKelompoklbl.setForeground(new java.awt.Color(0, 0, 0));
        namaKelompoklbl.setText("Kelompok 5 :");

        anggota1Lbl.setForeground(new java.awt.Color(0, 0, 0));
        anggota1Lbl.setText("210711438");

        anggota2Lbl.setBackground(new java.awt.Color(0, 0, 0));
        anggota2Lbl.setForeground(new java.awt.Color(0, 0, 0));
        anggota2Lbl.setText("210711446");

        javax.swing.GroupLayout datakelompokLblLayout = new javax.swing.GroupLayout(datakelompokLbl);
        datakelompokLbl.setLayout(datakelompokLblLayout);
        datakelompokLblLayout.setHorizontalGroup(
            datakelompokLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datakelompokLblLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datakelompokLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaKelompoklbl)
                    .addGroup(datakelompokLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(anggota1Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anggota2Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        datakelompokLblLayout.setVerticalGroup(
            datakelompokLblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datakelompokLblLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaKelompoklbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anggota1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anggota2Lbl)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datakelompokLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addGap(228, 228, 228))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLbl)
                    .addComponent(datakelompokLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        actionpanel.setBackground(new java.awt.Color(204, 204, 204));

        idvehicleLbl.setForeground(new java.awt.Color(0, 0, 0));
        idvehicleLbl.setText("Id Vehicle");

        brandVehicleLbl.setForeground(new java.awt.Color(51, 51, 51));
        brandVehicleLbl.setText("Vehicle Brand");

        productionYearLbl.setForeground(new java.awt.Color(0, 0, 0));
        productionYearLbl.setText("Production Year");

        platNumberLbl.setForeground(new java.awt.Color(0, 0, 0));
        platNumberLbl.setText("Plat Number");

        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputActionPerformed(evt);
            }
        });

        brandVehicleinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandVehicleinputActionPerformed(evt);
            }
        });

        productionYearInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productionYearInputActionPerformed(evt);
            }
        });

        platNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platNumberInputActionPerformed(evt);
            }
        });

        addBtn.setForeground(new java.awt.Color(0, 0, 0));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setForeground(new java.awt.Color(0, 0, 0));
        updateBtn.setText("Edit");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setForeground(new java.awt.Color(0, 0, 0));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionpanelLayout = new javax.swing.GroupLayout(actionpanel);
        actionpanel.setLayout(actionpanelLayout);
        actionpanelLayout.setHorizontalGroup(
            actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actionpanelLayout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionpanelLayout.createSequentialGroup()
                        .addGroup(actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, actionpanelLayout.createSequentialGroup()
                                .addGroup(actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(productionYearLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(platNumberLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productionYearInput)
                                    .addComponent(platNumberInput)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, actionpanelLayout.createSequentialGroup()
                                .addGroup(actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(brandVehicleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(idvehicleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(brandVehicleinput)
                                    .addComponent(idInput))))
                        .addGap(29, 29, 29))))
        );
        actionpanelLayout.setVerticalGroup(
            actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionpanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn))
                .addGap(29, 29, 29)
                .addGroup(actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idvehicleLbl)
                    .addComponent(idInput))
                .addGap(31, 31, 31)
                .addGroup(actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandVehicleLbl)
                    .addComponent(brandVehicleinput))
                .addGap(28, 28, 28)
                .addGroup(actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productionYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productionYearLbl))
                .addGap(31, 31, 31)
                .addGroup(actionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(platNumberLbl)
                    .addComponent(platNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        searchPanel.setBackground(new java.awt.Color(204, 204, 204));

        searchBtn.setForeground(new java.awt.Color(0, 0, 0));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchInput, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        action2Panel.setBackground(new java.awt.Color(204, 204, 204));

        totalPassengerLbl.setForeground(new java.awt.Color(0, 0, 0));
        totalPassengerLbl.setText("Total Passenger");

        strokeTypeLbl.setForeground(new java.awt.Color(0, 0, 0));
        strokeTypeLbl.setText("Stroke Type");

        buttonGroup1.add(CarRBtn);
        CarRBtn.setForeground(new java.awt.Color(0, 0, 0));
        CarRBtn.setText("Car");
        CarRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarRBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(motorcycleRBtn);
        motorcycleRBtn.setForeground(new java.awt.Color(0, 0, 0));
        motorcycleRBtn.setText("Motorcycle");
        motorcycleRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorcycleRBtnActionPerformed(evt);
            }
        });

        saveBtn.setForeground(new java.awt.Color(0, 0, 0));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setForeground(new java.awt.Color(0, 0, 0));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout action2PanelLayout = new javax.swing.GroupLayout(action2Panel);
        action2Panel.setLayout(action2PanelLayout);
        action2PanelLayout.setHorizontalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(action2PanelLayout.createSequentialGroup()
                        .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(action2PanelLayout.createSequentialGroup()
                                .addComponent(CarRBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(274, 274, 274))
                            .addGroup(action2PanelLayout.createSequentialGroup()
                                .addComponent(motorcycleRBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(237, 237, 237)))
                        .addGap(96, 96, 96))
                    .addGroup(action2PanelLayout.createSequentialGroup()
                        .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalPassengerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(action2PanelLayout.createSequentialGroup()
                                .addComponent(strokeTypeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalPassengerInput, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(strokeTypeInput))
                        .addGap(67, 67, 67))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action2PanelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        action2PanelLayout.setVerticalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action2PanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(CarRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPassengerLbl)
                    .addComponent(totalPassengerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(motorcycleRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(strokeTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strokeTypeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(action2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(actionpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(action2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        dataCarLbl.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        dataCarLbl.setForeground(new java.awt.Color(0, 0, 0));
        dataCarLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataCarLbl.setText("Data Car");

        dataMotoLbl1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        dataMotoLbl1.setForeground(new java.awt.Color(0, 0, 0));
        dataMotoLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataMotoLbl1.setText("Data Motorcycle");

        dataCarTxa.setColumns(20);
        dataCarTxa.setRows(5);
        jScrollPane1.setViewportView(dataCarTxa);

        dataMotoTxa.setColumns(20);
        dataMotoTxa.setRows(5);
        jScrollPane2.setViewportView(dataMotoTxa);

        javax.swing.GroupLayout showDataPanelLayout = new javax.swing.GroupLayout(showDataPanel);
        showDataPanel.setLayout(showDataPanelLayout);
        showDataPanelLayout.setHorizontalGroup(
            showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(showDataPanelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(dataCarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(263, 263, 263)
                .addComponent(dataMotoLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(106, 106, 106))
        );
        showDataPanelLayout.setVerticalGroup(
            showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataCarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataMotoLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(showDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        Kendaraan type = kc.searchDataKendaraan(searchInput.getText());
        setComponent(true);
        idInput.setEnabled(false);
        action = "update";
        CarRBtn.setEnabled(false);
        motorcycleRBtn.setEnabled(false);
        if(type.getJenis().equalsIgnoreCase("car")){
            strokeTypeInput.setEnabled(false);
        }else{
            totalPassengerInput.setEnabled(false);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInputActionPerformed

    private void brandVehicleinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandVehicleinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandVehicleinputActionPerformed

    private void productionYearInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productionYearInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productionYearInputActionPerformed

    private void platNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platNumberInputActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        setComponent(true);
        clearTxt();
        searchBtn.setText("");
        action = "add";
    }//GEN-LAST:event_addBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
       try{
           Kendaraan k;
       
           InvalidIdException();
//           isEmptyException();
           chooseTypeException();
           
           if(action.equalsIgnoreCase("add")==true){
               int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Are you Sure want to adding data ?", "Confirm", JOptionPane.YES_NO_OPTION);
               if(getAnswer == JOptionPane.YES_OPTION){
                   if(CarRBtn.isSelected() == true){
                   type = "Car";
                    k = new Kendaraan(idInput.getText(), brandVehicleinput.getText(),type, Integer.parseInt(productionYearInput.getText()), platNumberInput.getText()
                            ,Integer.parseInt(totalPassengerInput.getText()), "");
                        kc.insertDataKendaraan(k);
                    }else{
                        type = "Motorcycle";
                         k = new Kendaraan(idInput.getText(), brandVehicleinput.getText(),type, Integer.parseInt(productionYearInput.getText()), platNumberInput.getText()
                            ,0, strokeTypeInput.getText());
                        kc.insertDataKendaraan(k);
                    }
                    JOptionPane.showMessageDialog(null, "Successfully adding data...");
               }else{
                   JOptionPane.showMessageDialog(null, "Canceled Adding Data...");
               }
           }else{
               int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Are you Sure want to Edit data ?", "Confirm", JOptionPane.YES_NO_OPTION);
               if(getAnswer == JOptionPane.YES_OPTION){
                   if(CarRBtn.isSelected() == true){
                   k = new Kendaraan(idInput.getText(), brandVehicleinput.getText(),"Car", Integer.parseInt(productionYearInput.getText()), platNumberInput.getText()
                            ,Integer.parseInt(totalPassengerInput.getText()), "");
                        kc.updateDataKendaraan(k, searchInput.getText());
                    }else{
                        k = new Kendaraan(idInput.getText(), brandVehicleinput.getText(),"Motorcycle", Integer.parseInt(productionYearInput.getText()), platNumberInput.getText()
                            ,0, strokeTypeInput.getText());
                            kc.updateDataKendaraan(k, searchInput.getText());
                   }
                   JOptionPane.showMessageDialog(null, "Successfully Editing data...");
               }else{
                   JOptionPane.showMessageDialog(null, "Canceled Editing Data...");
            }
           }
           clearTxt();
           showData();
           setComponent(false);
           setEditDeleteBtn(false);
           
           
       }catch(InvalidIDException e){
           JOptionPane.showMessageDialog(this, e.message());
//       }catch(IsEmptyException e){
//           JOptionPane.showMessageDialog(this, e.message());
       }catch(ChooseTypeException e){
           JOptionPane.showMessageDialog(this, e.message());
       }catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void CarRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarRBtnActionPerformed
       motorcycleRBtn.setEnabled(false);
       strokeTypeInput.setEnabled(false);
    }//GEN-LAST:event_CarRBtnActionPerformed

    private void motorcycleRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorcycleRBtnActionPerformed
        CarRBtn.setEnabled(false);
        totalPassengerInput.setEnabled(false);
    }//GEN-LAST:event_motorcycleRBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearTxt();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "are you sure want to delete the data ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(getAnswer == JOptionPane.YES_OPTION){
            try{
                kc.deleteDataKendaraan(idInput.getText());
                clearTxt();
                showData();
                setEditDeleteBtn(false);
                JOptionPane.showMessageDialog(null, "Succesfully deleting Data...");
            }catch(Exception e){
                System.out.println(e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Cancel deleting Data...");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        setEditDeleteBtn(true);
        setComponent(false);
        try{
           Kendaraan findVehicle = kc.searchDataKendaraan(searchInput.getText());
           if(findVehicle == null){
               JOptionPane.showMessageDialog(null, "Data Not Found !", "Confirmation", JOptionPane.DEFAULT_OPTION);
           }else{
               idInput.setText(findVehicle.getId());
               brandVehicleinput.setText(findVehicle.getMerk());
               productionYearInput.setText(Integer.toString(findVehicle.getTahunPembuatan()));
               platNumberInput.setText(findVehicle.getNoPlat());
               totalPassengerInput.setText(Integer.toString(findVehicle.getJumlah_penumpang()));
               strokeTypeInput.setText(findVehicle.getJenis_tak());
               if(totalPassengerInput.getText().isEmpty()){
                   motorcycleRBtn.setSelected(true);
                   CarRBtn.setSelected(false);
               }else{
                   motorcycleRBtn.setSelected(false);
                   CarRBtn.setSelected(true);
               }
           }
       }catch(Exception e){
            System.out.println(e);
       }
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CarRBtn;
    private javax.swing.JPanel action2Panel;
    private javax.swing.JPanel actionpanel;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel anggota1Lbl;
    private javax.swing.JLabel anggota2Lbl;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel brandVehicleLbl;
    private javax.swing.JTextField brandVehicleinput;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel dataCarLbl;
    private javax.swing.JTextArea dataCarTxa;
    private javax.swing.JLabel dataMotoLbl1;
    private javax.swing.JTextArea dataMotoTxa;
    private javax.swing.JPanel datakelompokLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idvehicleLbl;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton motorcycleRBtn;
    private javax.swing.JLabel namaKelompoklbl;
    private javax.swing.JTextField platNumberInput;
    private javax.swing.JLabel platNumberLbl;
    private javax.swing.JTextField productionYearInput;
    private javax.swing.JLabel productionYearLbl;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel showDataPanel;
    private javax.swing.JTextField strokeTypeInput;
    private javax.swing.JLabel strokeTypeLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField totalPassengerInput;
    private javax.swing.JLabel totalPassengerLbl;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
